# Generated by Django 3.1.5 on 2021-02-25 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("^['А-Я']['а-я']+", message='месяц должен начинаться с большой буквы, кириллицей')], verbose_name='Haзвaниe месяца'),
        ),
        migrations.AlterField(
            model_name='month',
            name='name_int',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Порядковый номер месяца в году'),
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('name', 'name_int')},
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2040)], verbose_name='Период год')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duty.month', verbose_name='Период месяц')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'ordering': ['-year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
