# Generated by Django 3.1.5 on 2021-02-25 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_auto_20210225_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2040)], verbose_name='Период год'),
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='1')),
                ('day2', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='2')),
                ('day3', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='3')),
                ('day4', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='4')),
                ('day5', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='5')),
                ('day6', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='6')),
                ('day7', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='7')),
                ('day8', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='8')),
                ('day9', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='9')),
                ('day10', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='10')),
                ('day11', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='11')),
                ('day12', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='12')),
                ('day13', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='13')),
                ('day14', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='14')),
                ('day15', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='15')),
                ('day16', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='16')),
                ('day17', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='17')),
                ('day18', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='19')),
                ('day20', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='20')),
                ('day21', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='21')),
                ('day22', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='22')),
                ('day23', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='23')),
                ('day24', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='24')),
                ('day25', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='25')),
                ('day26', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='26')),
                ('day27', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='27')),
                ('day28', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='29')),
                ('day30', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='30')),
                ('day31', models.DecimalField(decimal_places=2, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='31')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duty.period', verbose_name='Период')),
            ],
        ),
    ]
