# Generated by Django 3.1.5 on 2021-02-25 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_auto_20210225_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name': 'Рабочее время месяц', 'verbose_name_plural': 'Рабочее время месяцы'},
        ),
        migrations.AddField(
            model_name='workhours',
            name='day19',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='19'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='day29',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='29'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day10',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day11',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day12',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day13',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day14',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='14'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day15',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='15'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day16',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='16'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day17',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='17'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day18',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='18'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day20',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='20'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day21',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='21'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day22',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='22'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day23',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='23'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day24',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='24'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day25',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='25'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day26',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='26'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day27',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='27'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day28',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='28'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day30',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='30'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day31',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='31'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day4',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day5',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day6',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day7',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day8',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day9',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='9'),
        ),
    ]
