# Generated by Django 3.1.5 on 2021-02-25 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_auto_20210225_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhours',
            name='days_quantity',
            field=models.PositiveSmallIntegerField(default=28, help_text='количество дней в месяце', validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(31)], verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='day1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='рабочее время, ч.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='1'),
        ),
    ]
