# Generated by Django 3.1.5 on 2021-02-25 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_auto_20210225_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator("^['А-Я']['а-я']+", message='фамилия должна начинаться с большой буквы, кириллицей')], verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("^['А-Я']['а-я']+", message='имя должно начинаться с большой буквы, кириллицей')], verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("^['А-Я']['а-я']+", message='отчество должно начинаться с большой буквы, кириллицей')], verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
