# Generated by Django 3.1.5 on 2021-02-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0006_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='SupportLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Линия поддержки',
                'verbose_name_plural': 'Линия поддержки',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='commandline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duty.commandline', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='employees',
            name='supportline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duty.supportline', verbose_name='Линия поддержки'),
        ),
    ]
